name: ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2
     
      - name: Start ZAP Docker container
        run: |    
          docker run --name zap -d -p 8080:8080 owasp/zap2docker-stable zap.sh --user root -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      
      - name: Install zap-cli
        run: |
          docker exec zap "apt-get update && apt-get install -y python3 python3-pip" 
          docker exec zap pip3 install python-owasp-zap-v2.4 
      
      - name: ZAP Scan
        run: |
          sudo docker exec zap zap-cli quick-scan --spider -r -o report.html https://insmeal.com

        
      - name: Copy ZAP report to runner
        run: docker cp zap:/zap/wrk/insmeal.com/report.html .
      
      - name: Stop ZAP Docker container
        run: docker stop zap


