name: ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2
      
      - name: Start ZAP Docker container
        run: |
          docker run --name zap -u zap -p 8080:8080 -d owasp/zap2docker-weekly zap.sh -daemon -port 8080
          docker exec zap /zap/zap.sh -cmd -addoninstall ascanrulesBeta -addoninstall pscanrulesBeta -addoninstall t1000 -addoninstall jbrofuzz
        
      - name: ZAP Scan
        run: |
          docker exec zap zap-cli quick-scan -s xss,sqli -t https://insmeal.com/

        
      - name: Copy ZAP report to runner
        run: docker cp zap:/zap/wrk/insmeal.com/report.html .
      
      - name: Stop ZAP Docker container
        run: docker stop zap


