name: ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install OWASP ZAP
      run: |
        sudo apt-get update
        sudo apt-get install -y zaproxy
        
    - name: Configure ZAP Proxy
      run: |
        zap.sh -daemon -port 8080
        
    - name: ZAP Scan
      run: |
        # Start ZAP scan
        session_id=$(curl -s http://localhost:8080/JSON/core/action/newSession/ | jq -r '.session')
        scan_url="http://localhost:8080/JSON/ascan/action/scan/?zapapiformat=JSON&url=https://insmeal.com/&recurse=&inScopeOnly="
        scan_id=$(curl -s $scan_url | jq -r '.scan')
    
        # Wait for ZAP to complete the scan
        status="0"
        while [ "$status" != "100" ]
        do
            status=$(curl -s "http://localhost:8080/JSON/ascan/view/status/?scanId=$scan_id&zapapiformat=JSON" | jq -r '.status')
            echo "Scan status: $status"
            sleep 5
        done
    
        # Generate ZAP report
        report_url="http://localhost:8090/JSON/core/view/report/?reportId=0&format=JSON"
        report=$(curl -s $report_url)
        echo "$report"


