name: ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2
      
     # - name: Install Docker
     #   uses: docker/setup-docker@v1
     
      - name: Start ZAP Docker container
        run: |
          # docker run --name zap -u zap -p 8080:8080 -d owasp/zap2docker-weekly zap.sh -daemon -port 8080
          docker run --name zap -d -p 8080:8080 owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      
      #- name: Install zap-cli
      #  run: sudo apt-get update && sudo apt-get install -y python3 python3-pip
        
      - name: Install zap-cli
        run: |
          docker exec zap /bin/sh -c "sudo apt-get update && sudo apt-get install -y python3 python3-pip" 
          docker exec zap pip3 install python-owasp-zap-v2.4 
      
      - name: ZAP Scan
        run: |
          # docker exec zap zap-cli quick-scan -s xss,sqli -t https://insmeal.com/
          sudo docker exec zap zap-cli quick-scan --spider -r -o report.html https://insmeal.com

        
      - name: Copy ZAP report to runner
        run: docker cp zap:/zap/wrk/insmeal.com/report.html .
      
      - name: Stop ZAP Docker container
        run: docker stop zap


